# 齒輪紀念品

這一章，我們會介紹怎樣設計一個簡單的齒輪紀念品，用來熟習齒輪的運作和繪畫。

<img src="image-20240213181349198.png" alt="image-20240213181349198" style="width:45%;" />

[toc]

## 1. 正齒輪(Spur Gear)、螺旋齒輪(Helical Gear)和人字齒輪(Herringbone Gear)

在上面的齒輪，我們可明顯見到，跟我們常見的Tamiya齒輪有所不同。它們的名字叫**人字齒輪(Herringbone Gear)**。



正齒輪、螺旋齒輪和人字齒輪都是機械傳動中常見的齒輪類型，它們之間的關係和區別主要體現在齒形結構和運動性能上：

- **正齒輪(Spur Gear)**：這是一種圓柱形齒輪，其齒與軸平行，應用最為廣泛，也是最容易製造的。

- **螺旋齒輪(Helical Gear)**：這是一種帶有螺旋齒的圓柱形齒輪。與正齒輪相比，螺旋齒輪可以承受更大的載荷，運行更為平穩，並且在工業中被廣泛使用。然而，其缺點是在運行時會產生軸向推力。

- **人字齒輪(Herringbone Gear)**：這是由兩個方向相反的螺旋齒輪組合而成的齒輪，因此軸向推力可以互相抵消，故無軸向推力，但製造較為困難。

<img src="image-20240213224306314.png" alt="image-20240213224306314" style="width:50%;" />

在工業上，人字齒輪(Herringbone Gear)比正齒輪更能承受載荷，又沒有螺旋齒輪的軸向推力問題，而且在旋轉時齒輪能自對正，不會有軸向移動，從動齒輪(driven gear)無需加入止推環或卡簧，減少工序。而在3D打印生產時，生產人字齒輪沒有了工藝上的製造困難，因此，3D打印生產的話，十分推薦使用人字齒輪。

##2. 生成齒輪

要造上述的齒輪紀念品，第一步要生成兩個尺寸的齒輪。

一般沉積式3D打印機，都是用0.4mm直徑的噴嘴，所能列印最少的模數是0.8mm，如果尺寸再少的話，解像度便不夠，這次我們選擇用1mm模數，分別製作**兩隻30齒**和**一隻15齒**的人字齒輪。



### 2.1 齒輪一

#### 2.1.1 生成齒輪

參考上一章，在`create`中，找到`Helical Gear+`。

<div style="text-align: CENTER"><img src="image-20240213224827779.png" alt="image-20240213224827779" style="zoom:100%;" /><img src="image-20240213224850916.png" alt="image-20240213224850916" style="zoom:100%;" /></div>

- 在第一版中，`Module`為`1mm`，`Helix Angle`為`30°`，`Teeth`為`30`，`Gear Width`為`4`mm，**剔選`Herringbone`** 。

- 在第二版中，選擇`Standard`為`Radial`，其他參數保持不變，就能生成一隻上下對稱的人字齒輪。



<img src="image-20240213225002766.png" alt="image-20240213225002766" style="zoom:100%;" /><img src="image-20240213224926732.png" alt="image-20240213224926732" style="zoom:100%;" />

可以在左方的樹狀欄中，見到這隻齒輪的模數並非1模數，而是0.866模數(也就是$\cos30\degree$​​)，這是因為齒輪是根據軸向平面投影而劃的，所以模數會少一點，但只要度一下齒距圓，就會發現齒距圓是`30mm`。



#### 2.1.2 加入齒輪間隙(Backlash)

==這時生成的齒輪，是不能直接3D打印的，因沒有預留間隙，尺寸會太大，卡著不能旋轉，必須要加入齒輪間隙(Backlash)。==

有兩個方法：

1. 在上述生成齒輪時的第二版，直接調整`Backlash`、`Addendum`和`Dedendum`三個參數，但這個方法我不推薦，因用插件生成的齒輪，是沒有歷史紀錄的，生成後就不能更改這三個參數
2. 用`offset face`將齒輪的面全部向內偏移

下面用的是方法二。



<div style="text-align: CENTER"><img src="image-20240214170500836.png" alt="image-20240214170500836" style="width:25%;" /><img src="select face.gif" alt="select face" style="width:45%;" /></div>

- 圖一：
	- 在Fusion360的最右上角，找到`SELECT`
	- 點選`Window Selection`，或按快捷鍵`1`
	- 之後到最下方的`Selection Filters`，只點選`Body Faces`
- 圖二：
	- 在正視或側視圖，按著滑鼠左鍵，由==右下到左上角==通過齒輪
	- 不要通過頂和底兩個面



<img src="image-20240214170632935.png" alt="image-20240214170632935" style="width:45%;" /><img src="image-20240214170735771.png" alt="image-20240214170735771" style="width:45%;" />

- 將視角移動一下，確保只選擇了齒輪的邊
- 用`offset face`，將所有齒牙偏移`-0.125mm`



####2.1.3 加工齒輪

<img src="image-20240213231648093.png" alt="image-20240213231648093" style="width:45%;" /><img src="image-20240213232210414.png" alt="image-20240213232210414" style="width:45%;" />

- 圖一：

	- **點選零件樹上齒輪邊的小黑點**
	- 在齒輪表面開一個新的草圖

- 圖二：

  - 劃一個圓通過齒根，並將其用快捷鍵`x`轉為作圖線
  - 用快捷鍵`o`，劃一個偏移`2mm`的圓
  - 用快捷鍵`l`和`x`，劃一條垂直線和一條60度的作圖線
  - 用快捷鍵`o`，將這兩條線偏移`1mm`
  - 最後，用快捷鍵`c`，劃兩個分別`8.2mm`和`12mm`直徑的圓

  

  <img src="image-20240214150652735.png" alt="image-20240214150652735" style="width:45%;" /><img src="image-20240213232554450.png" alt="image-20240213232554450" style="width:45%;" />

- 圖一：

	- 將剛劃的草圖，用快捷鍵`e`擠出，並在`extend type`中，用`To Object`穿到底

- 圖二：

  - 用快捷鍵`f`，將四邊修圓`1mm`

  	

  <img src="image-20240214150748319.png" alt="image-20240214150748319" style="width:60%;" />

- 最後就可以用`Circular Pattern`：
	- 在`Object Type`中選取`Features`，選取左下角的擠出和修圓的feature
	- `Axis`點選z軸，或點解pitch circle
	- `Quantity`選`6`，就能成功複雜6份
	- 如果遇到旋轉複製時有困難，可以試著將`Compute Type`由`Adjust`，改為`Optimized`或`Indentical`試試。



### 2.2 齒輪二

#### 2.2.1 生成齒輪

<img src="image-20240214150925831.png" alt="image-20240214150925831" style="width:32%;" /><img src="image-20240214151103289.png" alt="image-20240214151103289" style="width:32%;" /><img src="image-20240214151121379.png" alt="image-20240214151121379" style="width:32%;" />

- 圖一：
	- **先將小黑點褪回最上層**
	- 將30齒齒輪隱藏起來
- 圖二和三：
	- 在`create`中找到`Helical Gear+`
	- `Module`選擇`1mm`，`Helix Angle`選擇`-30°`(==螺旋齒輪需要具有一致的螺旋角，並且一個為正螺旋，一個為負螺旋，才能咬合==)
	- `Teeth`選擇`15`，`Gear Width`選`4mm`，剔選`Herringbone`
	- 在第二版中，`Standard`選擇`Radial`

#### 2.2.2 加入齒輪間隙

<img src="image-20240214175349092.png" alt="image-20240214175349092" style="width:50%;" />

- 跟上面的齒輪一樣，選擇齒輪的齒，用`offset face`偏移`-0.125mm`。



#### 2.2.3 加入中心孔

<img src="image-20240214152105978.png" alt="image-20240214152105978" style="width:45%;" /><img src="image-20240214152251543.png" alt="image-20240214152251543" style="width:45%;" />

- 圖一：
	- 檢查一下，模數跟齒輪一一致為0.866模數
	- **將小黑點點選到齒輪旁**
	- 在齒輪表面開一個新的草圖
- 圖二：
	- 劃一個直徑為`8.2mm`的圓
	- 用快捷鍵`e`，擠出，並選擇`To Object`，將其穿到齒輪底部



## 3. 制作外殼

### 3.1製作基礎外殼

<img src="image-20240214160622700.png" alt="image-20240214160622700" style="width:45%;" /><img src="image-20240214161135904.png" alt="image-20240214161135904" style="width:45%;" />

- 圖一：

	- **將小黑點褪回最上層**

	- 將小齒輪隱藏起來

	- 新增一個`new component`，名為`Shell`

- 圖二：

	- 在`TOP`中，開一個`new sketch`
	- 用`center to center slot`，劃一個`18mm`半徑，`33mm`長的槽
	- 用`midpoint`約束，用槽定在原點



<img src="image-20240214161824578.png" alt="image-20240214161824578" style="width:45%;" /><img src="image-20240214162357795.png" alt="image-20240214162357795" style="width:45%;" />

- 圖一：
	- 我們的大齒輪和小齒輪，齒距圓分別為`30mm`和`15mm`直徑，所以我們在槽的兩個中心點，劃兩個`30mm`直徑的圓
	- 在任意地方，劃一個`15mm`的圓，之後用`tangent`約束，將這個圓同時相切兩個`30mm`的圓
- 圖二：
	- 這個外殼厚`2mm`，所以我們用`offset`將槽向外偏移`2mm`



<img src="image-20240214163122435.png" alt="image-20240214163122435" style="width:45%;" /><img src="image-20240214163233655.png" alt="image-20240214163233655" style="width:45%;" />

- 圖一：
	- 選擇所有草圖，用快捷鍵`e`，向下擠出`2mm`
- 圖二：
	- 在零件樹中，將隱藏了的草圖`Sketch1`顯示出來
	- 將外殼部分向上擠出`6mm`



<img src="image-20240214163612670.png" alt="image-20240214163612670" style="width:45%;" /><img src="image-20240214163913075.png" alt="image-20240214163913075" style="width:45%;" />

- 圖一：
	- 隱藏`Sketch1`，在頂視圖點選外殼內部，開一個`new sketch`
- 圖二：
	- 將`Sketch1`重新顯示，用快速鍵`P`投影3個圓心
	- 接著就可以將`Sketch1`隱藏



<img src="image-20240214165005418.png" alt="image-20240214165005418" style="width:45%;" /><img src="image-20240214165121761.png" alt="image-20240214165121761" style="width:45%;" />

- 圖一：
	- 在三個圓心，分別劃三個`7.6mm`的圓
	- 在中間的圓心，外劃一個`15mm`的圓
- 圖二：
	- 用快捷鍵`e`，將三個小圓擠出，`Extend Type`選擇`To Object`，就能選擇外殼的高度



<img src="image-20240214165201925.png" alt="image-20240214165201925" style="width:45%;" /><img src="image-20240214165806675.png" alt="image-20240214165806675" style="width:45%;" />

- 圖一：
	- 將`Sketch2`重新顯示，點選`15mm`的圓，用快捷鍵`e`，切去外殼部分
	- `Extend Type`選`To Object`，點選外殼的高度
- 圖二：
	- 隱藏`Sketch2`後，就會得到這樣的一個外殼



<img src="image-20240214175925971.png" alt="image-20240214175925971" style="width:45%;" /><img src="image-20240214180007411.png" alt="image-20240214180007411" style="width:45%;" />

<img src="image-20240214180103801.png" alt="image-20240214180103801" style="width:45%;" /><img src="image-20240214180241674.png" alt="image-20240214180241674" style="width:45%;" />

- 圖一：將剛剛切的面，用`offset face`向外偏移`5mm`
- 圖二：將四邊用快捷鍵`f`，修成`3mm`半徑的孤
- 圖三：由於打印方向，圓柱體與平面很容易會斷，需要用`chamfer`，加入`1mm`的倒角
- 圖四：最後得出的成果



### 3.2 加入卡扣

<img src="image-20240214180937782.png" alt="image-20240214180937782" style="width:45%;" /><img src="image-20240214181005545.png" alt="image-20240214181005545" style="width:45%;" />

- 在其中一個軸的表面，開一個新的草圖
- 用快捷鍵`p`，將3個軸的表面都投影到這個草圖



<img src="image-20240214181319488.png" alt="image-20240214181319488" style="width:45%;" /><img src="image-20240214181606018.png" alt="image-20240214181606018" style="width:45%;" />

- 圖一：
	- 將最外的圓形`offset`偏移`0.4mm`
	- 加入一條穿過圓心的作圖線(可以用`coincident`2D約束)
	- 隨意在圓周劃兩條線, 用平行`parallel`和對稱`Symmetry`2D約束，劃一條`0.6mm`的槽
- 圖二：
	- 將圖一的步驟重覆兩次，尺寸可以點選之前的尺寸，方便修改



<img src="image-20240214203758436.png" alt="image-20240214203758436" style="width:45%;" /><img src="image-20240214203858850.png" alt="image-20240214203858850" style="width:45%;" />

- 圖一：
	- 按快捷鍵`e`擠出
	- 點選三個偏移了的圓如圖
- 圖二：
	- 向下擠出`0.8mm`



<img src="image-20240214203955152.png" alt="image-20240214203955152" style="width:45%;" />  <img src="image-20240214204121076.png" alt="image-20240214204121076" style="width:45%;" />

- 圖一：
	- 用`Chamfer`功能，將剛擠出的圓修`0.5mm`的倒角，做成一個卡扣，令齒輪易入難出
- 圖二：
	- 將`0.6mm`的槽，向下切`-5.5mm`，令齒輪一開始卡入時，軸能有點彈性，令齒輪易入難出



<img src="image-20240214211515063.png" alt="image-20240214211515063" style="width:50%;" />

- 跟三條軸一樣，垂直方向列印的話，殼壁會很易斷，所以加一個`1mm`的倒角



### 3.3 加入鎖匙圈

<img src="image-20240214212400364.png" alt="image-20240214212400364" style="width:45%;" /><img src="image-20240214212425691.png" alt="image-20240214212425691" style="width:45%;" />

- 在外殼中間，開一個`new sketch`
- 用快捷鍵`p`，將輻的圓心投影到上面的草圖上



<img src="image-20240214212548284.png" alt="image-20240214212548284" style="width:45%;" /><img src="image-20240214212717795.png" alt="image-20240214212717795" style="width:45%;" />

- 劃二個分別為`3.5mm`和`8mm`的圓，距離投影的軸`22.5mm`
- 用快捷鍵`e`向上擠出`4mm`



<img src="image-20240214212758381.png" alt="image-20240214212758381" style="width:50%;" />

- 用快捷鍵`f`修圓`3mm`就完成

## 4. 組合

<img src="image-20240214213527815.png" alt="image-20240214213527815" style="width:45%;" /><img src="image-20240214213737184-1707917858305-2.png" alt="image-20240214213737184" style="width:45%;" />

- 圖一：
	- 將小黑點褪回最上層
	- 將之前隱藏了的齒輪都顯示出來
- 圖二：
	- 用快捷鍵`j`將齒輪和外殼組合，點選齒輪表面和軸的表面，之後向下偏移`1mm`，就會剛好穿過卡扣
	- **在`motion`頁面選擇`Revolute`**



<img src="image-20240214214504172.png" alt="image-20240214214504172" style="width:45%;" /><img src="motion.gif" alt="motion" style="width:45%;" />

- 圖一：
	- 小齒輪也是相同處理
	- `Offset Z`選擇`1mm`向下偏移
	- `Angle`選擇`15°`，剛好與大齒輪囓合
	- **記得在`motion`頁面選擇`Revolute`**，這裡就不展示了
- 圖二：
	- 用快捷鍵`s`，搜尋`motion link`
	- 分別點選兩個`joint`的icon，或直接到零件樹中找到兩個joint
	- 大齒輪會比小齒輪轉慢一倍，我`Revolute1`是大齒輪，`Revolute2`是小齒輪，所以大齒輪轉`180°`時，小齒輪已轉了`360°`(如果是其他比倒，也可以用同樣方法調節)
	- 剔選`Reverse`，就會見到跟實物十分相似的效果



<img src="image-20240214220829170.png" alt="image-20240214220829170" style="width:45%;" /><img src="image-20240214220923400.png" alt="image-20240214220923400" style="width:45%;" />

- 圖一：
	- 只要複製多一隻大齒輪
	- 跟之前一樣用快捷鍵`j`組合到另一條輻上
	- 記得同樣要旋轉`15°`和z輻偏移`1mm`
- 圖二：
	- 加入`motion link`，將旋轉比例設為2:1，並剔選`Reverse`，就能見到三隻齒輛一起旋轉
- 最後，只要在零件樹將外殼`ground`，就能得到能模擬直實轉動的模型

## 5. (選項)加入曲面文字

Fusion 360有一項功能可以在將平面的草圖，彎曲環繞到曲面上



<img src="image-20240214221521201.png" alt="image-20240214221521201" style="width:45%;" /><img src="image-20240214221900681.png" alt="image-20240214221900681" style="width:45%;" />

- 圖一：
	- 將小黑點點到`shell`的旁邊
	- 點選外殼的平面，開一個新的草圖
- 圖二：
	- 用指令`text`就能劃出文字，文字高度選`5mm`
	- 只要將後面的曲面用快捷鍵`p`投影到這個平面上，就能將文字框完全對齊原點
	- 選一款喜歡的字型，最好盡量粗和工整的字體，太幼的話3D打印出來效果未必好
	- (不是所有字型都可以用到擠出功能，中文字體很多都不能擠出的)



<img src="image-20240214221949408.png" alt="image-20240214221949408" style="width:45%;" /><img src="image-20240214222049503.png" alt="image-20240214222049503" style="width:50%;" />

- 用快捷鍵`s`搜尋`emboss`功能
- `Sketch Profiles`選擇剛才的文字(注意文字不能逐字母選擇，只能一整個`text`的文字選擇)
- `Faces`選擇後面的曲面
- `Emboss`可以做到凹凸兩種選項，`depth`為`0.5mm`的話，無論是凹面或凸面，3D打印都可以不加支撐就能打印出來

## 6. 本章重點

1. **螺旋齒輪和人字齒輪都有更好的荷載，而人字齒輪沒有軸向偏移，更能自對正，不用外加卡簧和限位器**
2. **3D打印齒輪，必須加入齒輪間隙，可以用`offset face`來完成，方便調試間隙值**
3. **Joint可以用`motion link`來連動，方便模擬效果**
